//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwoFunctional.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OwoFunctional.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0~Explosion~100,1,90,0,0,0,|0%100,1%100,3%100,2%100,7%100,6%100,9%100,8%100&amp;40,19,80,0,1700,0,|0%100,1%100,3%100,2%100,7%100,6%100,8%100,9%100~impact-6~.
        /// </summary>
        internal static string Explosion {
            get {
                return ResourceManager.GetString("Explosion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1~HitWall~30,2,80,0,0,0,|0%100,1%100,2%100,3%100~impact-2~.
        /// </summary>
        internal static string HitWall {
            get {
                return ResourceManager.GetString("HitWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2~MissedNote~50,3,72,0,200,0,|9%100,8%100~impact-10~.
        /// </summary>
        internal static string MissedNote {
            get {
                return ResourceManager.GetString("MissedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3~RecoilBlade_L~81,3,60,100,100,0,|5%100,7%100~weapon-4~.
        /// </summary>
        internal static string RecoilBlade_L {
            get {
                return ResourceManager.GetString("RecoilBlade_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4~RecoilBlade_R~81,3,60,100,100,0,|4%100,6%100~weapon-4~.
        /// </summary>
        internal static string RecoilBlade_R {
            get {
                return ResourceManager.GetString("RecoilBlade_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5~Start~100,3,70,0,0,0,|0%100,1%100&amp;100,3,70,0,0,0,|0%100,1%100,5%100,4%100&amp;100,3,70,0,200,0,|0%100,1%100,4%100,5%100,3%100,2%100&amp;100,19,60,0,1900,0,|7%100,6%100,9%100,8%100~magic-2~.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
